# Generated by Django 4.1.5 on 2023-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('projectPhoto', models.CharField(max_length=50)),
                ('projectLink', models.CharField(max_length=1000)),
                ('projectText', models.CharField(max_length=1000)),
            ],
        ),
    ]
