# Generated by Django 4.1.5 on 2023-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_name',
            name='projectPhoto',
            field=models.CharField(max_length=2000),
        ),
    ]
