# Generated by Django 4.1.5 on 2023-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_name',
            name='skillLength',
            field=models.IntegerField(),
        ),
    ]
